In [1]:
import numpy as np


def sigmoid(x):
    ans = 1 / (1 + np.exp(-x))
    return ans


def softmax(x):
    x = np.exp(x)
    total = np.sum(x)
    y = x / total
    return y

In [2]:
def identity_function(x):
    return x


def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network


def forword(network, x):
    # layer 1
    W1 = network['W1']
    b1 = network['b1']
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)

    # layer 2
    W2 = network['W2']
    b2 = network['b2']
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)

    # layer 3
    W3 = network['W3']
    b3 = network['b3']
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)

    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forword(network, x)
print(y)

[0.31682708 0.69627909]


In [3]:
import numpy as np
import random


def sigmoid(x):
    ans = 1 / (1 + np.exp(-x))
    return ans


def identity_function(x):
    return x


def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network


def forword(network, x):
    # layer 1
    W1 = network['W1']
    b1 = network['b1']
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)

    # layer 2
    W2 = network['W2']
    b2 = network['b2']
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)

    # layer 3
    W3 = network['W3']
    b3 = network['b3']
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)

    return y

network = init_network()
batch_size = 16
x = np.random.rand(1000, 2)
for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forword(network, x_batch)
    print("batch : %d" % i)
    print(y_batch)


batch : 0
[[0.31471736 0.69159214]
 [0.31652309 0.69558976]
 [0.31438485 0.69084046]
 [0.31614934 0.69476068]
 [0.31560585 0.69355042]
 [0.31397724 0.68993419]
 [0.3126506  0.6870048 ]
 [0.315047   0.69231609]
 [0.30896336 0.6788223 ]
 [0.31310176 0.68799333]
 [0.31424971 0.69055366]
 [0.31807164 0.69904049]
 [0.31867132 0.700374  ]
 [0.3135807  0.68904971]
 [0.31053105 0.68229052]
 [0.31570015 0.69376085]]
batch : 16
[[0.31500542 0.69221314]
 [0.31613119 0.69472399]
 [0.31317853 0.68816072]
 [0.31005729 0.68124367]
 [0.31571603 0.69380031]
 [0.31671527 0.69601531]
 [0.31353074 0.68894585]
 [0.31248124 0.68662817]
 [0.31540296 0.69310411]
 [0.31259179 0.68685876]
 [0.31377145 0.68948057]
 [0.31232498 0.68627739]
 [0.31281983 0.68737611]
 [0.31391164 0.6897938 ]
 [0.31863112 0.70028726]
 [0.31494967 0.69210915]]
batch : 32
[[0.31634139 0.69518934]
 [0.31355436 0.68899059]
 [0.31537762 0.69305901]
 [0.31656509 0.69568056]
 [0.31650021 0.69554091]
 [0.31451499 0.69113036]
 [0.31073796 0.6